micronaut :
  application :
    name : smartmirror-backend
  server :
    cors :
      enabled : true
      configurations :
        web :
          allowedOrigins :
            - http://localhost:3000
  router :
    static-resources :
      default :
        paths : classpath:frontend
        mapping : /**
        enabled : true
  security :
    reject-not-found : false
    authentication : cookie
    endpoints :
      login :
        path : api/account/login
      logout :
        path : api/account/logout
        get-allowed : true
    redirect :
      enabled : false
    token :
      jwt :
        signatures :
          secret :
            generator :
              secret : ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
        generator :
          access-token :
            expiration : 7776000
    oauth2 :
      clients :
        spotify :
          client-id : ${SPOTIFY_OAUTH_CLIENT_ID:""}
          client-secret : ${SPOTIFY_CLIENT_SECRET:""}
          scopes :
            - user-read-currently-playing
            - user-read-playback-state
          authorization :
            url : https://accounts.spotify.com/authorize
          token :
            url : https://accounts.spotify.com/api/token
            auth-method : client-secret-post
      callback-uri : /api/services/auth{/provider}/callback
      login-uri : /api/services/auth{/provider}/login
r2dbc :
  datasources :
    default :
      url : ${JDBC_URL:`r2dbc:h2:mem:///smartmirror;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
      username : ${JDBC_USER:root}
      password : ${JDBC_PASSWORD:}
      schema-generate : ${JDBC_SCHEMA_GENERATE:create_drop}
      dialect : ${JDBC_DIALECT:mysql}
smartmirror :
  services :
    openweathermap :
      token : ${OPEN_WEATHER_MAP_TOKEN:""}