micronaut :
  security :
    enabled : true
    reject-not-found : false
    authentication : cookie
    oauth2 :
      clients :
        spotify :
          client-id : ${OAUTH_CLIENT_ID}
          client-secret : ${OAUTH_CLIENT_SECRET}
          scopes :
            - user-read-currently-playing
            - user-read-playback-state
          authorization :
            url : https://accounts.spotify.com/authorize
          token :
            url : https://accounts.spotify.com/api/token
            auth-method : client-secret-post
  application :
    name : smartmirror-backend
