micronaut :
  security :
    enabled : false
    reject-not-found : false
    authentication : cookie
    oauth2 :
      clients :
        spotify :
          client-id : ${SPOTIFY_OAUTH_CLIENT_ID:""}
          client-secret : ${SPOTIFY_CLIENT_SECRET:""}
          scopes :
            - user-read-currently-playing
            - user-read-playback-state
          authorization :
            url : https://accounts.spotify.com/authorize
          token :
            url : https://accounts.spotify.com/api/token
            auth-method : client-secret-post
        mso :
          client-id : ${MSO_OAUTH_CLIENT_ID:""}
          client-secret : ${SPOTIFY_OAUTH_CLIENT_SECRET:""}
          authorization :
            url : https://marienschule.com/oauth/authorize
          token :
            url : https://marienschule.com/oauth/token
            auth-method : client_secret_post
          openid :
            issuer : https://marienschule.com
  application :
    name : smartmirror-backend
  router :
    static-resources :
      default :
        paths : classpath:frontend
        mapping : /**
        enabled : true
r2dbc :
  datasources :
    default :
      url : ${R2DBC_URL:`r2dbc:mysql://127.0.0.1:3306/smartmirror`}
      username : ${JDBC_USER:root}
      password : ${JDBC_PASSWORD:}
      schema-generate : create_drop
      dialect : ${JDBC_DIALECT:mysql}
smartmirror :
  services :
    openweathermap :
      token : ${OPEN_WEATHER_MAP_TOKEN:""}